### ISSUE TITLE
ID2JOSM - add input

### ISSUE THREAD

**Issue by nlehuby** [simonpoole/preset-utils#3]
I'm trying to convert some presets from in ID fork with ID2JOSM. But the urls for the fields and presets files are hard-coded in the source code (and they return a 404).
Could you consider adding them as an input for the script ?

**Comment by simonpoole** [comment]
The utility was really a one off for generating data for a SOTM talk and hadn't been updated since. 

https://github.com/simonpoole/preset-utils/commit/4fdcb791937843fda3d44139af853105b12bdc92 fixes most of the issues resulting from bitrot and adds the ability to use non-default locations of the input files.
~~You can test if the changes work for you with this jar (remove the .txt that is just to make github happy)~~

**Comment by nlehuby** [comment]
:thinking: it sounds good without the new parameters, but not with them:
* `java -cp preset-utils-all-0.29.0.jar ch.poole.osm.presetutils.ID2JOSM` is ok
* `java -cp preset-utils-all-0.29.0.jar ch.poole.osm.presetutils.ID2JOSM 
--fieldsurl https://raw.githubusercontent.com/openstreetmap/id-tagging-schema/main/dist/fields.json 
--preseturl https://raw.githubusercontent.com/openstreetmap/id-tagging-schema/main/dist/presets.json 
--translationurl https://raw.githubusercontent.com/openstreetmap/id-tagging-schema/main/dist/translations/en.json  -o id_presets.xml` returns GRAVE: Problem converting presets: null

**Comment by simonpoole** [comment]
Hmm, I'm still working on a couple of odd bits and pieces due to changes in the schema, I'll check the URL issue as soon as I'm finished with that.

**Comment by simonpoole** [comment]
> it sounds good without the new parameters, but not with them

Was just a small oversight.
